### ISSUE TITLE
Conditionizr v5.0

### ISSUE THREAD

**Issue by toddmotto** [conditionizr/conditionizr#43]
I'd like to discuss the future API for Conditionizr, topics of discussion:
#### Detects

I think we should move away from just "environment" detects, and promote the fact users can add feature detects and not just environment detects, so we should include `/features/` directory with things like `cssTransforms.js` inside to get the best of both worlds for the end developer.
#### Asynchronous file loading

Currently we can load JS/CSS files, but we have zero information as to when the request has finished so that the developer can instantiate plugins/scripts that rely on the conditional loading. This is fine for CSS, however for JS async files need instantiating once available.

Possible ways to do this:

``` js
// has an anonymous function as the callback
conditionizr.load('/fastclick.js', 'ios', function () {
    // fastclick.js has loaded
});

// namespace the event and instantiate when available
conditionizr.load('fastclick', '/fastclick.js', 'ios');

conditionizr.on('fastclick', function () {
    // fastclick.js has loaded
});
```

I'm not sure which I prefer currently, but this seems crucial to our next feature integration.

We could also look at the top level `config` Object as a host for loading all these async files:

``` js
conditionizr.config({
  assets: '/path/to/my/assets/',
  load: {
    'fastclick': { // use the prop name as event namespace
        file: '/fastclick.js',
        run: ['ios', 'safari']
    }
  }
  tests: {
    'safari': ['script', 'style', 'class']
  }
});

conditionizr.on('fastclick', function () {
    // fastclick.js has loaded
});
```

Other points to discuss, should we deprecate/merge the `['script', 'style', 'class']` feature in favour of this new file syntax. I'm not sure how I feel about the `script/style` loading feature, however I love the `class` capability of conditionizr so would want to keep this.

@nfq @markgoodyear

**Comment by nfq** [comment]
**Detects**
Yes, I totally agree. I think feature detection is important. I have a collection of feature detects setup using Conditionizr, things like: classlist, flexbox, geolocation, cutting the mustard check etc. Here's my regular setup: https://gist.github.com/nfq/9ccb2e2b59f96e669f31. Not, the JS detection is kind of hackish.

**Asynchronous file loading**
I agree, this is crucial. I stumbled on this problem today, where for example I don't need Fastclick for Firefox or Chrome, but need it for iOS 9 <. Ideally, you only want to load the script on the browser/environment in question. Syntax wise, I prefer:

```javascript
// has an anonymous function as the callback
conditionizr.load('/fastclick.js', 'ios', function () {
    // fastclick.js has loaded
});
```
**['script', 'style', 'class']**
I always use 'class'. And until recently never used the others. But thinking about it, there might be projects where an ie8.css might be needed, even if uncommon theses days. Thinking on these lines I think it's too soon to deprecate this feature, but merge might be smart.

**Thinking further**
I use bowser (https://github.com/ded/bowser) for browser version detection. I haven't thought it through but having something like this built into Conditionizr would be the bee's knees. Essentially 'Conditionizr: for all your detection needs'.

**Comment by markgoodyear** [comment]
#### Detects
Yup, this I agree with too, I rarely use browser detection in favour of feature detection if I need to make sure what I'm doing is supported. Are you proposing a `browsers/` and `features/` folder?

#### Asynchronous file loading
I also prefer the syntax @nfq mentioned, makes sense to me. The `environment` param would need to support an array to allow multiple environments. Generally I imagine it would be singular though, but you never know what people need.

#### ['script', 'style', 'class']
Whilst I do like the idea of the script and style, with the async file loading it's potentially redundant. I think depreciating it along with some docs to help users using them migrate would be good.

#### Extra: npm modules
I mentioned to Todd about this, but I'd love to see some form of modular detects and get it up on npm. It'd be awesome (at least I think so :wink:) to do something like this:

```js
import Conditionizr from 'conditionizr';
import ios from 'conditionizr-detects';

Conditionizr.add('ios', ios);
```

Or something like that, making it easy to grab the Conditionizr core, then grab detect packages — maybe split into `conditionizr-browsers` and `conditionizr-features`.

**Comment by Ne-Ne** [comment]
Whats the progress on this so far?
