### ISSUE TITLE
Touch Support

### ISSUE THREAD

**Issue by Ne-Ne** [conditionizr/conditionizr#45]
I personally love Modernizr, but I use Conditionizr for the browser classes, it works great! But I'm unsure on the effectiveness of the touch test.

However now that touch events have changes from v2 to v3 are you going depreciate or improve on the current touch.js test?

**Comment by toddmotto** [comment]
Gonna close this off as we don't maintain this as much - detecting touch isn't typically recommended either due to touch screen machines (Windows Surface etc)
