### ISSUE TITLE
Safari detection is broken in Safari Technology Preview

### ISSUE THREAD

**Issue by cdumez** [conditionizr/conditionizr#46]
The following is currently used to detect Safari:
/Constructor/.test(window.HTMLElement)

as per:
https://github.com/conditionizr/conditionizr/blob/master/detects/safari.js

However, it does not work in the Safari Technology Preview which now behaves like other browsers in this respect. You can download Safari Technology Preview at:
https://developer.apple.com/safari/download/

**Comment by cdumez** [comment]
So this detection mechanism works until Safari 9.x but will likely break in the next major Safari release.

**Comment by dylanhthomas** [comment]
Currently, safari detection is broken

**Comment by QandnotU** [comment]
Hoping to get some love on this.

**Comment by sebet** [comment]
Would also like to see this issue resolved. Is this project still active?

**Comment by toddmotto** [comment]
We don't actively work on the project anymore, but the latest API allows you to create your own detects - if you find one that works for you please PR! :)

**Comment by toddmotto** [comment]
If you guys can test this, possibly on older Safari versions as well - but it's working for me (just paste this in your browser console):

```js
/constructor/i.test(window.HTMLElement) || (function (p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || safari.pushNotification);
```

**Comment by sebet** [comment]
@toddmotto, thanks for the reply.

That seems to work.

Would something like this work:

````

**Comment by QandnotU** [comment]
@sebet replacing the safari detect with the above seems to be working.

**Comment by toddmotto** [comment]
@sebet Nope that looks perfect, you could also use the non-function approach:

```js
var safariRegex = /constructor/i.test(window.HTMLElement) || (function (p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || safari.pushNotification);
conditionizr.add( 'safari', safariRegex);
```

**Comment by sebet** [comment]
Perfect! Thanks for your help @toddmotto. If this can somehow be added officially at some point to the library it would be great. 

Until then I'll use the the custom test.

**Comment by toddmotto** [comment]
Cleaned it up a little and added to the core: https://github.com/conditionizr/conditionizr/blob/master/detects/safari.js

**Comment by QandnotU** [comment]
Thanks @toddmotto for giving this some love.
